### ISSUE TITLE
Updated crystal version?

### ISSUE THREAD

**Issue by f1reflyyyylmao** [jreinert/gpg.cr#2]
# What are you trying to do?
I try to compile my program using your gpg bindings using crystal 0.30.1

# What's wrong?
It won't compile and errors out with a message that I believe is linked to the lib you created

# So wheres the message?
Here: 
```
 % crystal build --verbose  src/syncchanges.cr
BUG: trying to upcast Int32 <- LibGPG::Error (Exception)
Unhandled exception: Error opening file 'crystal' with mode 'r': No such file or directory (Errno)
Failed to raise an exception: END_OF_STACK
[0x562524901a46] ???
[0x562523f9549b] __crystal_raise +43
[0x562523f96c35] ???
[0x562523fa2131] ???
[0x562523f9b61a] ???
[0x562523f9aaf7] ???
[0x562524310f20] ???
[0x562523fabf3d] ???
[0x562523f98eb7] main +55
[0x7f082fdd1ee3] __libc_start_main +243
[0x562523f9154e] _start +46
[0x0] ???
%
```

# Can't you just create a pull request for me to accept?
I'm afraid I can't, I've never worked with C bindings before :(

**Comment by repomaa** [comment]
Hey,

I don't expect everyone to just fix every bug they find. Great job for pointing this one out and giving a good description of it. :) I'll try and fix this asap!

**Comment by repomaa** [comment]
Can reproduce running the specs.

**Comment by repomaa** [comment]
Fixed! Thanks again!

**Comment by f1reflyyyylmao** [comment]
Great, thank you for your work :)
